# For Importing Files

In [1]:
import os
import pandas as pd
import numpy as np
import requests
#from dotenv import load_dotenv

In [2]:
BASE_ID = "appKAJE1ZTvFZnxJ4"
TOKEN_NAME = "Orders Summary"
API_KEY = "key9tcxlWbfKeps7M"

In [3]:
global offset
offset = '0'
raw_data = []

while True :
    url = f"https://api.airtable.com/v0/{BASE_ID}/{TOKEN_NAME}"
    querystring = {
        "view":"All Orders List",
        "api_key":f"{API_KEY}",
        "offset": offset}

    try :
        response= requests.get(url, params=querystring)
        response_Table = response.json()
        records = list(response_Table['records'])
        raw_data.append(records)
        #print(records[0]['id'] , len(records))
    
        try : 
            offset = response_Table['offset']
            #print(offset)
            
        except Exception as ex:
            #print(ex , offset)
            break
    
    except error as e:
        print(e)

In [4]:
all_data = [d['fields'] for data in raw_data for d in data]

In [5]:
final_cols = []
for d,data in enumerate(all_data):
    for col in data:
        if type(all_data[d][col])==list:
            if len(all_data[d][col]) > 1:
                for i,_ in enumerate(all_data[d][col]):
                    if i==0:
                        idx = col
                    else:
                        idx = col+"_"+str(i)
                    if idx not in final_cols:
                        final_cols.append(idx)
            else:
                if col not in final_cols:
                        final_cols.append(col)
        else:    
            if col not in final_cols:
                final_cols.append(col)

In [6]:
final_data = pd.DataFrame(columns = final_cols, index = [i for i in range(len(all_data))])

In [7]:
for d,data in enumerate(all_data):
    for col in data:
        if type(all_data[d][col])==list:
            if len(all_data[d][col]) > 1:
                for i,_ in enumerate(all_data[d][col]):
                    if i==0:
                        idx = col
                    else:
                        idx = col+"_"+str(i)
                    final_data[idx][d] = all_data[d][col][i]
            else:
                final_data[col][d] = all_data[d][col][0]
        elif type(all_data[d][col]) not in [list,int,str,float]:
            final_data[col][d] = np.nan
        else:    
            final_data[col][d] = all_data[d][col]

In [8]:
final_data

,Order Number,Products,Tracking Code,Status,Customer Name,Invoice Number,PO Number,Other Comments,Source,Shipping Company,...,Description (from Products)_18,Description (from Products)_19,Description (from Products)_20,Description (from Products)_21,RMA Number_1,RMA Adjustment_1,PO Number_11,PO Number_12,PO Number_13,PO Number_14
0,100001275,recNofyVu6nRwnaPT,9400109699939617685058,Completed,recjHYZF5ahVPHdG0,receNhcz9cPDEp91m,rec2ODmWziREXrNuG,MC Order,PPC (Direct Order),USPS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100006224,recLtazf0y4AOevGm,UK Order Adjustment,Completed,recpWIy69LsDJRlTi,recHNflZO4Bx3pI11,rec6aW4YhnbugXlI8,NaN,Repeat Buying/Customer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100006225,recch0jCraF2OLvvr,UK Order Adjustment,Completed,recpWIy69LsDJRlTi,recIx1RtmH06BaBIa,recdnoIVmcYa3SO65,NaN,Repeat Buying/Customer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000004773,recHA1lVi5N0TZu3t,1Z639F720320007616,Completed,recClu0l4j5luWoG6,rechK5VH4vDLRKpCd,recTKsvv5n2x72NmN,Sent & Posted,PPC (Direct Order),UPS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000004784,rec7J9o2ORrtbtO1s,9461509699937531078399,Completed,recBGREZr8P8fjzGF,recRV4eXCrOU4122d,recn9E2S9wRKxVnfv,Sent & Posted,PPC (Direct Order),USPS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11228,1000022888,reckuD0sUUsoj9J7f,276991381733,Completed,rec6B5t9qGP94W3n2,recXHpUS6dccBzJME,recmx9ytWULwbQ4ib,NaN,Live Chat,FedEx,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11229,1000022891,recuhMjMGk9wsKcDF,NaN,Out of Stock (Cancelled),recYEnpaA9r3TigH0,NaN,NaN,NaN,PPC (Direct Order),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11230,1000022893,recuKiAabnZ2pXjnJ,276994046240,Completed,recTfLVCAlmn65oT9,recz0lMc7a7qcLVTL,rec83DhvKOWiTRUKX,NaN,Repeat Buying/Customer,FedEx,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11231,1000022894,recl4tl1Bp1fNjeqt,NaN,Pending,recfRBpt3bwRNVL2B,NaN,NaN,NaN,PPC (Direct Order),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11232,1000022895,recFTttk0fajmfAyG,NaN,Completed,recWaWPM3I6F4givV,recaE8mLRWzKDfxzc,rec87NldHnpShQxIi,NaN,Live Chat,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
for d,data in enumerate(all_data):
    for col in data:
        if type(all_data[d][col]) not in [list,int,str,float]:
            #print(col)
            print(all_data[d][col])

{'error': '#ERROR!'}
{'specialValue': 'NaN'}
{'specialValue': 'NaN'}
{'error': '#ERROR!'}
{'specialValue': 'NaN'}

In [16]:
sorted(final_cols)

['Actual Order Amount',
 'Actual Order Amount_1',
 'Actual Order Amount_2',
 'Alternate Part (Y/N)',
 'Alternate Part#',
 'Alternate part #',
 'Brand',
 'Brand Name',
 'Brand Name 2',
 'Brand Name 2_1',
 'Brand Name 2_10',
 'Brand Name 2_11',
 'Brand Name 2_12',
 'Brand Name 2_13',
 'Brand Name 2_14',
 'Brand Name 2_15',
 'Brand Name 2_16',
 'Brand Name 2_17',
 'Brand Name 2_18',
 'Brand Name 2_19',
 'Brand Name 2_2',
 'Brand Name 2_20',
 'Brand Name 2_3',
 'Brand Name 2_4',
 'Brand Name 2_5',
 'Brand Name 2_6',
 'Brand Name 2_7',
 'Brand Name 2_8',
 'Brand Name 2_9',
 'Brand Name_1',
 'Brand Name_10',
 'Brand Name_11',
 'Brand Name_12',
 'Brand Name_13',
 'Brand Name_14',
 'Brand Name_15',
 'Brand Name_16',
 'Brand Name_17',
 'Brand Name_18',
 'Brand Name_19',
 'Brand Name_2',
 'Brand Name_20',
 'Brand Name_3',
 'Brand Name_4',
 'Brand Name_5',
 'Brand Name_6',
 'Brand Name_7',
 'Brand Name_8',
 'Brand Name_9',
 'Brand_1',
 'Brand_10',
 'Brand_11',
 'Brand_12',
 'Brand_13',
 'Brand_14',
 'Brand_15',
 'Brand_16',
 'Brand_17',
 'Brand_18',
 'Brand_19',
 'Brand_2',
 'Brand_20',
 'Brand_3',
 'Brand_4',
 'Brand_5',
 'Brand_6',
 'Brand_7',
 'Brand_8',
 'Brand_9',
 'Category Name',
 'Category Name_1',
 'Category Name_2',
 'Category Name_3',
 'Category Name_4',
 'Category Name_5',
 'Category Name_6',
 'Category Name_7',
 'Category Name_8',
 'Customer Email',
 'Customer Name',
 'Customer Name_1',
 'Customer Name_2',
 'Description (from Products)',
 'Description (from Products)_1',
 'Description (from Products)_10',
 'Description (from Products)_11',
 'Description (from Products)_12',
 'Description (from Products)_13',
 'Description (from Products)_14',
 'Description (from Products)_15',
 'Description (from Products)_16',
 'Description (from Products)_17',
 'Description (from Products)_18',
 'Description (from Products)_19',
 'Description (from Products)_2',
 'Description (from Products)_20',
 'Description (from Products)_21',
 'Description (from Products)_3',
 'Description (from Products)_4',
 'Description (from Products)_5',
 'Description (from Products)_6',
 'Description (from Products)_7',
 'Description (from Products)_8',
 'Description (from Products)_9',
 'Division',
 'GP Without Shipping',
 'Gross Profit',
 'Invoice Amount',
 'Invoice Number',
 'Invoice Number_1',
 'Order Date',
 'Order Date & Time',
 'Order Date & Time_1',
 'Order Date & Time_2',
 'Order Date_1',
 'Order Date_2',
 'Order Number',
 'Other Comments',
 'PO Amount',
 'PO Number',
 'PO Number_1',
 'PO Number_10',
 'PO Number_11',
 'PO Number_12',
 'PO Number_13',
 'PO Number_14',
 'PO Number_2',
 'PO Number_3',
 'PO Number_4',
 'PO Number_5',
 'PO Number_6',
 'PO Number_7',
 'PO Number_8',
 'PO Number_9',
 'Payment Status',
 'Payment Status (Inv.)',
 'Payment Status (Inv.)_1',
 'Process Date',
 'Process Date & Time',
 'Processing Time (Hours)',
 'Products',
 'Products_1',
 'Products_10',
 'Products_11',
 'Products_12',
 'Products_13',
 'Products_14',
 'Products_15',
 'Products_16',
 'Products_17',
 'Products_18',
 'Products_19',
 'Products_2',
 'Products_20',
 'Products_21',
 'Products_3',
 'Products_4',
 'Products_5',
 'Products_6',
 'Products_7',
 'Products_8',
 'Products_9',
 'RMA Adjustment',
 'RMA Adjustment_1',
 'RMA Number',
 'RMA Number_1',
 'Sales Order',
 'Sales Order_1',
 'Sales Order_2',
 'Sales Orders',
 'Sales Person',
 'Shipping Company',
 'Shipping Cost',
 'Shipping Name',
 'Shipping Name_1',
 'Shipping Name_2',
 'Shipping Status',
 'Shipping paid',
 'Shipping paid_1',
 'Shipping paid_2',
 'Source',
 'Status',
 'Supplier Name',
 'Support Person',
 'Tax Amount (Inv.)',
 'Total Cost',
 'Tracking Code']

In [14]:
sheet_id = "1d2Qi4qaRi0Edb2IA-4S_IorOvfgTFk3V2O5cGcLsaU4"
sheet_name = "Sheet2"
sales_target_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
sales_person_target = pd.read_csv(sales_target_url)

## GETTING DAY,MONTH,YEAR

In [21]:
from datetime import datetime
def dateChecker(entry):
    if str(entry) != "nan":
        return datetime.strptime(entry,"%Y-%m-%d")
    else:
        return None

In [23]:
final_data['Order Date'] = final_data['Order Date'].apply(lambda x : dateChecker(x))

TypeError: strptime() argument 1 must be str, not Timestamp

In [24]:
final_data['Getting Year'] = final_data['Order Date'].apply(lambda x: x.year).replace(np.nan,0).apply(lambda y: int(y))
final_data['Getting Quarter'] = final_data['Order Date'].apply(lambda x: x.quarter).replace(np.nan,0).apply(lambda y: int(y))
final_data['Getting Month'] = final_data['Order Date'].apply(lambda x: x.month).replace(np.nan,0).apply(lambda y: int(y))
final_data['Getting Day'] = final_data['Order Date'].apply(lambda x: x.day).replace(np.nan,0).apply(lambda y: int(y))

C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\3083969477.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  final_data['Getting Year'] = final_data['Order Date'].apply(lambda x: x.year).replace(np.nan,0).apply(lambda y: int(y))
C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\3083969477.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  final_data['Getting Quarter'] = final_data['Order Date'].apply(lambda x: x.quarter).replace(np.nan,0).apply(lambda y: int(y))
C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\3083969477.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  final_data['Getting Month'] = final_data['Order Date'].apply(lambda x: x.month).replace(np.nan,0).apply(lambda y: int(y))
C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\3083969477.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  final_data['Getting Day'] = final_data['Order Date'].apply(lambda x: x.day).replace(np.nan,0).apply(lambda y: int(y))

In [40]:
final_data["Target Amount"] = [0 for _ in range(len(final_data))]
for d_idx in range(len(final_data)):
    for t_idx in range(len(sales_person_target)):
        if final_data["Sales Person"][d_idx] == sales_person_target["Sales Person"][t_idx] and final_data["Getting Year"][d_idx] == sales_person_target["Year"][t_idx] and final_data["Getting Quarter"][d_idx] == sales_person_target["Quarter"][t_idx]:
            final_data["Target Amount"][d_idx] = sales_person_target["Target Amount"][t_idx]

C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\4042376020.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  final_data["Target Amount"] = [0 for _ in range(len(final_data))]
C:\Users\Soul_Reaper_X\AppData\Local\Temp\ipykernel_10820\4042376020.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data["Target Amount"][d_idx] = sales_person_target["Target Amount"][t_idx]

In [41]:
final_data.columns

Index(['Order Number', 'Products', 'Tracking Code', 'Status', 'Customer Name',
       'Invoice Number', 'PO Number', 'Other Comments', 'Source',
       'Shipping Company',
       ...
       'RMA Adjustment_1', 'PO Number_11', 'PO Number_12', 'PO Number_13',
       'PO Number_14', 'Getting Year', 'Getting Quarter', 'Getting Month',
       'Getting Day', 'Target Amount'],
      dtype='object', length=192)

In [44]:
final_data["Target Amount"]

0            0
1            0
2            0
3            0
4            0
         ...
11228    20000
11229        0
11230    20000
11231        0
11232        0
Name: Target Amount, Length: 11233, dtype: int64